events {}
http {
  upstream auth_upstream { server auth-service:8000; }
  upstream case_upstream { server case-service:8000; }
  server {
    listen 80;

    location /api/auth/ {
      proxy_pass http://auth_upstream/api/auth/;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/cases/ {
      proxy_pass http://case_upstream/api/cases/;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /docs-auth {
      proxy_pass http://auth_upstream/docs;
    }

    location /docs-cases {
      proxy_pass http://case_upstream/docs;
    }
  }
}
