import { useMemo, useState } from 'react';
import { addDocumentMapping, applyRedactionDecision, deleteDocumentMapping, mergeDocumentMappings, reanonymizeDocument, repairPlaceholders, saveAnonymization, updateDocumentMapping } from '../../api/casesApi';
import type { EntityMapping } from '../../api/types';
import { DATE_PURPOSE_LABELS, ENTITY_TYPE_OPTIONS, getEntityTypeLabel, getSourceLabel, LOCATION_PURPOSE_LABELS, PERSON_ROLE_LABELS } from '../../constants/anonymizationLabels';
import RichDocumentEditor from '../documents/RichDocumentEditor';
import { plainTextToTiptapDocument } from '../../utils/tiptapDocument';

type Props = { documentId: string; caseId?: string; initialData?: any; onSaved?: () => void; sourceContent?: unknown; sourceText?: string };
const mappingsFrom = (data: any): EntityMapping[] => data?.mappings || data?.entity_mappings || data?.anonymization?.mappings || [];
const keptFrom = (data: any): EntityMapping[] => data?.recognized_but_kept || data?.anonymization?.recognized_but_kept || [];
const reviewFrom = (data: any): EntityMapping[] => data?.review_entities || data?.anonymization?.review_entities || [];
const textFrom = (data: any) => data?.anonymized_text || data?.anonymization?.anonymized_text || data?.anonymized_plain_text || '';
const contentFrom = (data: any) => data?.anonymized_content || null;

export default function AnonymizationWorkspace({ documentId, initialData, sourceText }: Props) {
  const [mappings, setMappings] = useState<EntityMapping[]>(mappingsFrom(initialData));
  const [recognizedButKept, setRecognizedButKept] = useState<EntityMapping[]>(keptFrom(initialData));
  const [reviewEntities, setReviewEntities] = useState<EntityMapping[]>(reviewFrom(initialData));
  const [tab, setTab] = useState<'REDACT'|'KEEP'|'REVIEW'>('REDACT');
  const [anonymizedText, setAnonymizedText] = useState(textFrom(initialData));
  const [anonymizedContent, setAnonymizedContent] = useState<any>(contentFrom(initialData));
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [targetId, setTargetId] = useState('');
  const [editId, setEditId] = useState<string | null>(null);
  const [editForm, setEditForm] = useState<any>({});
  const [redactionMode, setRedactionMode] = useState<'NORMATIVE' | 'EXTENDED_SAFE'>(initialData?.publication_redaction_mode || 'NORMATIVE');
  const [warning, setWarning] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [selectedText, setSelectedText] = useState(''); const [entityType, setEntityType] = useState('PERSON_FULL_NAME');

  const conflicts = useMemo(() => { const map = new Map<string, number>(); mappings.forEach((m) => m.placeholder && map.set(m.placeholder, (map.get(m.placeholder)||0)+1)); return new Set([...map.entries()].filter(([,c])=>c>1).map(([k])=>k)); }, [mappings]);
  const provider = initialData?.ner_provider || 'hybrid';
  const providerLabel: Record<string,string> = { hybrid: 'Natasha и правила', natasha: 'Natasha', regex: 'Только регулярные выражения', 'regex-fallback': 'Natasha недоступна, используются только правила' };

  const applyResponse = (data: any) => { setMappings(mappingsFrom(data)); setRecognizedButKept(keptFrom(data)); setReviewEntities(reviewFrom(data)); setAnonymizedText(textFrom(data)); setAnonymizedContent(contentFrom(data)); };
  const reanon = async () => { const res = await reanonymizeDocument(documentId, { mappings, publication_redaction_mode: redactionMode }); applyResponse(res.data); setWarning(''); };

  return <div className='anonymization-workspace'>
    <h2>Результат обезличивания</h2>
    <div className='redaction-mode-card'><h3>Режим обезличивания</h3><select value={redactionMode} onChange={(e)=>{setRedactionMode(e.target.value as any); setWarning('Режим обезличивания изменён. Выполните повторное обезличивание для применения новых правил.');}}><option value='NORMATIVE'>Нормативный режим публикации судебного акта</option><option value='EXTENDED_SAFE'>Расширенный безопасный режим</option></select><p>Система скрывает персональные данные участников дела в соответствии с правилами публикации судебных актов. ФИО судьи, секретаря и наименования организаций могут оставаться в тексте.</p><p>Система дополнительно скрывает контактные и иные потенциально идентифицирующие сведения, например электронную почту и спорные идентификаторы.</p><p><b>После изменения режима необходимо повторно выполнить обезличивание.</b></p></div>
    <div className='recognition-provider-card'><h3>Механизм распознавания</h3><p>Активный режим: {providerLabel[provider] || provider}</p><p>Найдено Natasha: {mappings.filter((m)=>m.source==='natasha').length}</p><p>Найдено регулярными выражениями: {mappings.filter((m)=>m.source==='regex').length}</p><p>Требует проверки: {reviewEntities.length}</p>{provider==='regex-fallback' && <p className='warning-message'>Модель Natasha не запущена. Качество распознавания ФИО может быть снижено.</p>}</div>
    {warning && <p className='warning-message'>{warning}</p>}{error && <p className='error-message'>{error}</p>}{message && <p className='success-message'>{message}</p>}
    {conflicts.size>0 && <div className='placeholder-conflict'>Обнаружен конфликт условных обозначений.</div>}
    {conflicts.size>0 && <button className='button danger-button' type='button' onClick={async()=>{try{const r=await repairPlaceholders(documentId);applyResponse(r.data);setWarning('');setMessage('Условные обозначения исправлены, текст документа обновлён.');}catch(e:any){setError(e?.response?.status===405||e?.response?.status===404?'Автоматическое исправление обозначений пока не поддерживается сервером.':'Не удалось исправить условные обозначения.');}}}>Исправить обозначения автоматически</button>}
    <RichDocumentEditor value={anonymizedContent || plainTextToTiptapDocument(anonymizedText)} editable onSelectionChange={setSelectedText} />

    <div className='entity-tabs'><button className='button button-secondary' onClick={()=>setTab('REDACT')}>Обезличено</button><button className='button button-secondary' onClick={()=>setTab('KEEP')}>Оставлено в тексте</button><button className='button button-secondary' onClick={()=>setTab('REVIEW')}>Требует проверки</button></div>
    {tab==='REDACT' && <div><div className='mapping-selection-toolbar'><p>Объединяйте записи только тогда, когда это разные варианты написания одного человека или объекта.</p><select value={targetId} onChange={(e)=>setTargetId(e.target.value)}><option value=''>Основная запись</option>{mappings.filter((m)=>m.id && selectedIds.includes(m.id)).map((m)=><option key={m.id} value={m.id}>{m.placeholder || m.original_value}</option>)}</select><button className='button button-secondary' onClick={async()=>{if(selectedIds.length<2){setError('Выберите не менее двух записей.');return;} if(!targetId || !selectedIds.includes(targetId)){setError('Основная запись должна входить в выбранные.');return;} const picked=mappings.filter((m)=>selectedIds.includes(m.id || '')); const mixed=new Set(picked.map((m)=>m.entity_type)).size>1; if(mixed && !window.confirm('Вы объединяете записи разных типов. Подтвердите действие.')) return; await mergeDocumentMappings(documentId,{target_mapping_id:targetId,source_mapping_ids:selectedIds.filter((id)=>id!==targetId)}); await reanon(); setSelectedIds([]);setTargetId('');}}>Объединить выбранные</button></div>
      <table className='mapping-table'><thead><tr><th></th><th>Условное обозначение</th><th>Основное значение</th><th>Тип данных</th><th>Роль/контекст</th><th>Источник</th><th>Действия</th></tr></thead><tbody>{mappings.map((m,i)=><tr key={m.id || i} className={editId===m.id?'mapping-edit-row':''}><td><input type='checkbox' checked={selectedIds.includes(m.id || '')} onChange={(e)=>{const id=m.id||'';setSelectedIds(e.target.checked?[...selectedIds,id]:selectedIds.filter((x)=>x!==id));}}/></td><td>{editId===m.id?<input value={editForm.placeholder||''} onChange={(e)=>setEditForm({...editForm,placeholder:e.target.value})}/>:m.placeholder||'—'}</td><td>{editId===m.id?<input value={editForm.original_value||''} onChange={(e)=>setEditForm({...editForm,original_value:e.target.value})}/>:m.original_value}</td><td>{editId===m.id?<select value={editForm.entity_type||''} onChange={(e)=>setEditForm({...editForm,entity_type:e.target.value})}>{ENTITY_TYPE_OPTIONS.map((o)=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:getEntityTypeLabel(m.entity_type)}</td><td>{editId===m.id?<input value={editForm.person_role||''} onChange={(e)=>setEditForm({...editForm,person_role:e.target.value})}/>:PERSON_ROLE_LABELS[m.person_role || m.role || ''] || m.context || DATE_PURPOSE_LABELS[m.date_purpose || ''] || LOCATION_PURPOSE_LABELS[m.location_purpose || ''] || '—'}</td><td>{getSourceLabel(m.source || m.detection_method)}</td><td>{editId===m.id?<><button className='button' onClick={async()=>{const r=await updateDocumentMapping(documentId,m.id!,editForm);setMappings(mappingsFrom(r.data));setEditId(null);setWarning('Запись таблицы соответствия изменена. Выполните повторное обезличивание.');}}>Сохранить</button><button className='button button-secondary' onClick={()=>setEditId(null)}>Отмена</button></>:<><button className='button button-secondary' onClick={()=>{setEditId(m.id||null);setEditForm(m);}}>Изменить</button><button className='danger-button' onClick={async()=>{await deleteDocumentMapping(documentId,m.id!);}}>Удалить</button></>}</td></tr>)}</tbody></table></div>}
    {tab==='KEEP' && (recognizedButKept.length ? <table className='mapping-table'><tbody>{recognizedButKept.map((m,i)=><tr key={i}><td>{m.original_value}</td><td>{m.redaction_reason || 'ФИО судьи оставлено в нормативном режиме'}</td></tr>)}</tbody></table> : <div className='empty-state'>Сущности этой категории не найдены.</div>)}
    {tab==='REVIEW' && (reviewEntities.length ? <table className='mapping-table'><tbody>{reviewEntities.map((m,i)=><tr key={i}><td>{m.original_value}</td><td>{getEntityTypeLabel(m.entity_type)}</td><td><button className='button' onClick={async()=>{await applyRedactionDecision(documentId,{selected_text:m.original_value,decision:'REDACT',entity_class:m.entity_class || m.entity_type || 'OTHER'});await reanon();}}>Обезличить</button><button className='button button-secondary' onClick={async()=>{await applyRedactionDecision(documentId,{selected_text:m.original_value,decision:'KEEP',entity_class:m.entity_class || m.entity_type || 'OTHER'});await reanon();}}>Оставить в тексте</button><button className='button button-secondary' onClick={async()=>{if(!mappings[0]?.cluster_id)return;await applyRedactionDecision(documentId,{selected_text:m.original_value,decision:'MERGE_WITH_EXISTING',entity_class:m.entity_class || m.entity_type || 'OTHER',target_cluster_id:mappings[0].cluster_id});await reanon();}}>Объединить с существующей записью</button><button className='button button-secondary' onClick={async()=>{await applyRedactionDecision(documentId,{selected_text:m.original_value,decision:'REDACT',entity_class:prompt('Уточните тип данных','OTHER') || 'OTHER'});await reanon();}}>Уточнить тип данных</button></td></tr>)}</tbody></table> : <div className='empty-state'>Сущности этой категории не найдены.</div>)}

    <section className='selection-panel'><h3>Выделенный фрагмент</h3><textarea readOnly value={selectedText} /><div className='form-grid'><select value={entityType} onChange={(e)=>setEntityType(e.target.value)}>{ENTITY_TYPE_OPTIONS.map((o)=><option key={o.value} value={o.value}>{o.label}</option>)}</select><button type='button' className='button' onClick={async()=>{if(!selectedText)return;const res=await addDocumentMapping(documentId,{ original_value:selectedText, entity_type:entityType, mode:'new'});setMappings(mappingsFrom(res.data));setWarning('После изменения таблицы соответствия выполните повторное обезличивание.');}}>Создать новую скрываемую сущность</button></div></section>
    <button className='button button-secondary' onClick={reanon}>Повторно обезличить</button>
    <button className='button' onClick={async()=>{await saveAnonymization(documentId,{anonymized_text:anonymizedText,mappings});}}>Сохранить документ</button>
    {sourceText && <p className='warning-message'>Исходный текст изменён. Таблица соответствия может быть неактуальна. Выполните обезличивание повторно.</p>}
  </div>;
}
